// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vEO5m9nAwF5_CNyGe2nd26Vi3ExqD68',
    appId: '1:223059417666:web:81e8cedd01d5e2212cabdb',
    messagingSenderId: '223059417666',
    projectId: 'dbvsing',
    authDomain: 'dbvsing.firebaseapp.com',
    databaseURL: 'https://dbvsing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dbvsing.appspot.com',
    measurementId: 'G-78242BY01H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1N-3PpNWzZRkQcHQKlXoeyI_WNKj0Y7E',
    appId: '1:223059417666:android:61e70e905729e0a82cabdb',
    messagingSenderId: '223059417666',
    projectId: 'dbvsing',
    databaseURL: 'https://dbvsing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dbvsing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVF9qnNBE62SWSFq9Np4TJ-s4a8hWFiqk',
    appId: '1:223059417666:ios:717166666b7415802cabdb',
    messagingSenderId: '223059417666',
    projectId: 'dbvsing',
    databaseURL: 'https://dbvsing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dbvsing.appspot.com',
    iosClientId: '223059417666-vghij4bqnvbar9eu2f3dqif47fede1g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.vsing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVF9qnNBE62SWSFq9Np4TJ-s4a8hWFiqk',
    appId: '1:223059417666:ios:717166666b7415802cabdb',
    messagingSenderId: '223059417666',
    projectId: 'dbvsing',
    databaseURL: 'https://dbvsing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dbvsing.appspot.com',
    iosClientId: '223059417666-vghij4bqnvbar9eu2f3dqif47fede1g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.vsing',
  );
}
